# Generated by Django 4.2.4 on 2023-09-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='imagen',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
