# Generated by Django 4.2.4 on 2023-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0002_rename_result_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='No Name', max_length=100, unique=True),
        ),
    ]
