# Generated by Django 4.2.4 on 2023-09-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0004_remove_schedule_points_schedule_hc_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(blank=True, max_length=2, null=True)),
                ('penalty', models.BooleanField()),
                ('definition_of_penalties', models.BooleanField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.player')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.schedule')),
            ],
        ),
    ]
