# Generated by Django 4.2.4 on 2023-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0004_player_grade_player_name_player_team_schedule_hc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hc_gol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('raining', 'Raining'), ('playing', 'Playing'), ('pending', 'Pending')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vs_gol',
            field=models.IntegerField(null=True),
        ),
    ]
