# Generated by Django 4.2.4 on 2023-09-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0005_schedule_date_schedule_hc_gol_schedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
