# Generated by Django 4.2.4 on 2023-09-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0006_rename_hc_gol_schedule_hc_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='mvp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.player'),
        ),
    ]
