# Generated by Django 4.2.4 on 2023-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0008_alter_schedule_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hc_definition_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vs_definition_penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
