# Generated by Django 4.2.4 on 2023-09-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0009_alter_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='team',
            name='abbrev',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
