# Generated by Django 4.2.4 on 2023-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0009_schedule_hc_definition_penalties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
