# Generated by Django 4.2.4 on 2023-09-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0010_alter_player_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
    ]
