# Generated by Django 4.2.4 on 2023-09-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0010_remove_team_logo_team_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
