# Generated by Django 4.2.4 on 2023-09-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0011_alter_player_name_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='stages',
            field=models.CharField(choices=[('regular', 'Regular'), ('octavos', 'Octavos'), ('cuartos', 'Cuartos'), ('semifinal', 'SemiFinal'), ('final', 'Final')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Nombre', max_length=100, unique=True),
        ),
    ]
