# Generated by Django 4.2.4 on 2023-09-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0011_remove_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.league'),
        ),
    ]
