# Generated by Django 4.2.4 on 2023-09-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0013_remove_player_league_remove_player_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='league',
            name='team',
            field=models.ManyToManyField(to='futbol.team'),
        ),
    ]
