# Generated by Django 4.2.4 on 2023-09-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0014_remove_team_league_league_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='leagues',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.CreateModel(
            name='PlayerLeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.team')),
            ],
        ),
    ]
