# Generated by Django 4.2.4 on 2023-09-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0015_remove_league_team_remove_player_leagues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(to='futbol.league'),
        ),
    ]
