# Generated by Django 4.2.4 on 2023-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0017_remove_team_leagues_league_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
