# Generated by Django 4.2.4 on 2023-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0018_team_slug_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
