# Generated by Django 4.2.4 on 2023-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0021_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
