# Generated by Django 4.2.4 on 2023-11-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0023_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('pj', models.IntegerField(blank=True, null=True)),
                ('pg', models.IntegerField(blank=True, null=True)),
                ('pe', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('gf', models.IntegerField(blank=True, null=True)),
                ('gc', models.IntegerField(blank=True, null=True)),
                ('gdif', models.IntegerField(blank=True, null=True)),
                ('liga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.league')),
                ('vs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.team')),
            ],
        ),
    ]
