# Generated by Django 4.2.4 on 2023-11-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0025_stat_pts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='liga',
            new_name='leaque',
        ),
    ]
