# Generated by Django 4.2.4 on 2023-11-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0026_rename_liga_stat_leaque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='leaque',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='vs',
            new_name='team',
        ),
    ]
