# Generated by Django 4.2.4 on 2023-11-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0027_rename_leaque_stat_league_rename_vs_stat_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hc_definition_penalties',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hc_goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hc_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vs_definition_penalties',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vs_goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vs_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
