# Generated by Django 4.2.4 on 2023-11-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0029_rename_stat_standing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hc_points',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='vs_points',
        ),
    ]
