# Generated by Django 4.2.4 on 2023-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0030_remove_schedule_hc_points_remove_schedule_vs_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
