# Generated by Django 4.2.4 on 2023-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0031_player_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='active',
        ),
        migrations.AddField(
            model_name='playerleagueteam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
