# Generated by Django 4.2.4 on 2023-09-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre', max_length=100, unique=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('abbrev', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('vs_gol', models.IntegerField(null=True)),
                ('hc_gol', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('raining', 'Raining'), ('playing', 'Playing'), ('pending', 'Pending')], default='scheduled', max_length=20)),
                ('stages', models.CharField(choices=[('regular', 'Regular'), ('octavos', 'Octavos'), ('cuartos', 'Cuartos'), ('semifinal', 'SemiFinal'), ('final', 'Final')], default='regular', max_length=20)),
                ('hc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hc_schedule', to='common.team')),
                ('vs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vs_schedule', to='common.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre', max_length=100, unique=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.team')),
            ],
        ),
    ]
